interface=wlan0
bind-interfaces
dhcp-authoritative
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,1h
domain=local
no-resolv
# Redirige cualquier dominio a la Pi (portal cautivo)
address=/#/192.168.4.1
# Log para debug
log-dhcp
