default-sample-format = s16le
default-sample-rate = 44100
default-sample-channels = 2
default-fragments = 8
default-fragment-size-msec = 50
resample-method = trivial
avoid-resampling = false
high-priority = true
nice-level = -11
realtime-scheduling = true
realtime-priority = 5
rlimit-rtprio = 9
daemonize = no
exit-idle-time = -1
